### ISSUE TITLE
Allow option to open in new tab.

### ISSUE THREAD

**Issue by Adithya-Kalany** [imreyesjorge/root-startpage#14]
Hello!

Since iframes are blocked from loading in another site, I would like the links to open in a new tab. Please advise solutions or add a option. Thank you!

**Comment by imreyesjorge** [comment]
Hello there @Adithya-Kalany 👋🏼,

This have a simple solution, just add ` <base target="_blank">` inside the `<head>` tag.

**Comment by Adithya-Kalany** [comment]
Oh okay, I thought I had to mess around with app.js, thanks!
