### ISSUE TITLE
Not an issue, more a question!

### ISSUE THREAD

**Issue by Normanras** [imreyesjorge/root-startpage#16]
I *love* this start page! I've been using it for a while and want to change something slightly, but can't seem to figure it out. 

I want one of my button cards to just copy the link to my clipboard instead of opening the page. I know how to create and call an `onclick` function, but since this is rendered dynamically in the `app.js` file, I'm not exactly sure where to add the function. 

I've tried adding a function with an if statement to the bottom of `app.js`, but it doesn't seem to work and continues to just open the webpage. I suppose when the card is created with the `<a` tag, I could say if the `currentCard.href` is `link_xyz`, add a script + onclick function? Not sure how nesting functions like that works in Javascript - I'm the least familiar with js. 

Any tips or suggestions?

**Comment by imreyesjorge** [comment]
Hello there @Normanras 👋🏻 

I'm happy to hear that you find _root_ useful. Just added this functionality to the project, to use it just add a new property to each card item you want to have this behavior.

It should look something like this: 

```js
{ 
   name: 'Discord', 
   icon: 'ri-discord-fill', 
   link: 'https://discord.com/app', 
   clipboard: true
}
```

**Comment by Normanras** [comment]
Woah! Thanks, man! I'm going to look through your code to see how you approached this and learn a bit. Appreciate your work.
