### ISSUE TITLE
Opening links in a new tab

### ISSUE THREAD

**Issue by deKoning** [imreyesjorge/root-startpage#21]
I love the start-page!

Would it be possible to add a function to define per card if it opens in a new tab/page of in the same window?

**Comment by imreyesjorge** [comment]
I’m more into delegate this to the browser itself. 

The default behavior is to open the link in the same page, but you can always use any browser shortcut to open the page in a new tab, such as, middle click or cmd + click (on macOs).

However, if you want to add this logic, feel free to fork the project and add it yourself.
