### ISSUE TITLE
[ Suggestion ] Spin up a demo of it on github pages

### ISSUE THREAD

**Issue by xelarate86** [imreyesjorge/root-startpage#4]
As in title - selfhosted crowd always appreciates a hands-on test

**Comment by MiguelRAvila** [comment]
@xelarate86 There's one right here: https://imreyesjorge.github.io/root-startpage/

**Comment by xelarate86** [comment]
Beauty - throwing it into the README along with its presence in "About" will ensure no one misses it. They'll also be able to see how it "feels" in production. Added pull request #5 for your review.

**Comment by imreyesjorge** [comment]
Thanks for your contribution @xelarate86 :smile:
