### ISSUE TITLE
Weekday is wrong

### ISSUE THREAD

**Issue by technowhizz** [imreyesjorge/root-startpage#9]
Hi,

The weekday shown is wrong.

**Comment by technowhizz** [comment]
You need to update DAYS from:
`const DAYS = [  "Monday",  "Tuesday",  "Wednesday",  "Thursday",  "Friday",  "Saturday",  "Sunday",];`

To:
`const DAYS = [ "Sunday", "Monday",  "Tuesday",  "Wednesday",  "Thursday",  "Friday",  "Saturday", ];`

**Comment by technowhizz** [comment]
Pull request created #10

**Comment by imreyesjorge** [comment]
Thanks for fixing the error!
